### ISSUE TITLE
Keep the message template instead of rendering it

### ISSUE THREAD

**Issue by cosminonea** [redboxllc/stackdriver-serilog#5]
It would be great to keep the message template as is:
```
 Logger.Information("Processing {MessageId}", message.Id);
```
This should log the message as is to make it easier to search for all instances of the same message across time.

This is the out of the box behaviour of the JsonFormatter.

**Comment by linjmeyer** [comment]
Merged in #9

**Comment by cosminonea** [comment]
Thanks for implementing this!

What would be the reason to log both the message and the messageTemplate. In my experience the rendered message is not that useful and it would also double the log size. It would be great to have the render/no render as a configuration rather than logging both.

**Comment by linjmeyer** [comment]
Personally I find the templates harder to read, when I have a lot of logs to go through a human readable format is easier for me.

That said, no issues with making it configurable so people can choose their preference.  Maybe an enum so you can do just the template, just the rendered result, or both?
