### ISSUE TITLE
Throw an exception of its own if the requested exception serializes to too long a payload

### ISSUE THREAD

**Issue by kieranbenton** [redboxllc/stackdriver-serilog#6]
Great library!

I've run into a situation where if I log exceptions with too much information embedded (usually where I've accidentally serialized say a request as JSON and included it) then Stackdriver receives the data but it ends up split over two lines.

That then means Stackdriver Error Reporting doesn't notice that the log is an error - and so exceptions get missed.

Fully appreciate this is a problem on my side - but thought it would be useful for the library to prevent misuse!

I'm not actually sure what the maximum line size is, but https://cloud.google.com/logging/quotas seems to suggest it might be 256kb all in?

Cheers.

**Comment by kieranbenton** [comment]
If you can give me some idea/conversation over what might be appropriate to do, then I can have a bash at giving you a PR.

**Comment by linjmeyer** [comment]
I'm curious, what happens when something json formatted gets split into two log entries?  They are accepted but just not queryable?

Seems reasonable to add the 256 limit though, I think an option to disable the limit would be good too in case anyone prefers it off.  PR would be welcome!

**Comment by kieranbenton** [comment]
Cool ok, I'm going to get a spike working in my local code base first, and will then drop you a PR with what I have in mind.

Pretty much yes, you get the raw JSON (or portion of JSON) shown in StackDriver Logs, and more crucially Error Reporting doesn't recognise exceptions and so errors get missed.

Basically I have two approaches:
1. If its an aggregate exception being logged - then log each inner exception separately with a cloned LogEvent
2. Track the character count written to the TextWriter and if it goes over 256kb (ish!) then still log but ALSO emit a short FATAL LogEvent indicating the problem to tell the consumer to fix their logging at source.

Does that sound reasonable? Right now I'll probably subclass TextWriter (ugh) and pass through calls to the TextWriter passed from Serilog (but track a count of characters).

**Comment by kieranbenton** [comment]
Sorry... Its been a while since I've opened a PR, hope that's roughly what is required? That PR covers just (2) from my above comment. 

I have a seperate patch to cover (1) if you'd like that as well?

**Comment by kieranbenton** [comment]
Having slept on it, I think that (1) should happen outside of this library.

**Comment by linjmeyer** [comment]
Merged in #7
